-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-- Script g�n�r� le 19/11/2012 - SGBD cible : MySql version 4
-- G�n�ration d'un script SQL � partir d'une base Access V 1.0 - Pierre Loisel - CERTA
-- > Les n� auto pour des attributs non cl� primaire ont �t� transform�s en INTEGER.
-- > Les tables g�n�r�es sont de ENGINE InnoDb.
-- > Les cl�s �trang�res ne sont g�r�es que si MySql g�re les tables InnoDb.
-- > Le jeu de caract�res utilis� est LATIN-1.
-- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
set names 'latin1';
create table `ACTIVITE_COMPL`(`AC_NUM` INT AUTO_INCREMENT not null,`AC_DATE` DATETIME,`AC_LIEU` VARCHAR(25),`AC_THEME` VARCHAR(10),`AC_MOTIF` VARCHAR(50),primary key(`AC_NUM`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `COMPOSANT`(`CMP_CODE` VARCHAR(4) not null,`CMP_LIBELLE` VARCHAR(25),primary key(`CMP_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `CONSTITUER`(`MED_DEPOTLEGAL` VARCHAR(10) not null,`CMP_CODE` VARCHAR(4) not null,`CST_QTE` FLOAT,primary key(`MED_DEPOTLEGAL`,`CMP_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `DOSAGE`(`DOS_CODE` VARCHAR(10) not null,`DOS_QUANTITE` VARCHAR(10),`DOS_UNITE` VARCHAR(10),primary key(`DOS_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `FAMILLE`(`FAM_CODE` VARCHAR(3) not null,`FAM_LIBELLE` VARCHAR(80),primary key(`FAM_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AA','Antalgiques en association');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAA','Antalgiques antipyr�tiques en association');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAC','Antid�presseur d\'action centrale');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AAH','Antivertigineux antihistaminique H1');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABA','Antibiotique antituberculeux');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABC','Antibiotique antiacn�ique local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ABP','Antibiotique de la famille des b�ta-lactamines (p�nicilline A)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AFC','Antibiotique de la famille des cyclines');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AFM','Antibiotique de la famille des macrolides');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AH','Antihistaminique H1 local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AIM','Antid�presseur imipraminique (tricyclique)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AIN','Antid�presseur inhibiteur s�lectif de la recapture de la s�rotonine');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ALO','Antibiotique local (ORL)');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('ANS','Antid�presseur IMAO non s�lectif');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AO','Antibiotique ophtalmique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AP','Antipsychotique normothymique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('AUM','Antibiotique urinaire minute');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('CRT','Cortico�de, antibiotique et antifongique � usage local');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('HYP','Hypnotique antihistaminique');
insert into `FAMILLE`(`FAM_CODE`,`FAM_LIBELLE`) values('PSA','Psychostimulant, antiasth�nique');
create table `FORMULER`(`MED_DEPOTLEGAL` VARCHAR(10) not null,`PRE_CODE` VARCHAR(2) not null,primary key(`MED_DEPOTLEGAL`,`PRE_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `INTERAGIR`(`MED_PERTURBATEUR` VARCHAR(10) not null,`MED_MED_PERTURBE` VARCHAR(10) not null,primary key(`MED_PERTURBATEUR`,`MED_MED_PERTURBE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `INVITER`(`AC_NUM` INT not null,`PRA_NUM` SMALLINT not null,`SPECIALISTEON` TINYINT(1),primary key(`AC_NUM`,`PRA_NUM`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `LABO`(`LAB_CODE` VARCHAR(2) not null,`LAB_NOM` VARCHAR(10),`LAB_CHEFVENTE` VARCHAR(20),primary key(`LAB_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `LABO`(`LAB_CODE`,`LAB_NOM`,`LAB_CHEFVENTE`) values('BC','Bichat','Suzanne Terminus');
insert into `LABO`(`LAB_CODE`,`LAB_NOM`,`LAB_CHEFVENTE`) values('GY','Gyverny','Marcel MacDouglas');
insert into `LABO`(`LAB_CODE`,`LAB_NOM`,`LAB_CHEFVENTE`) values('SW','Swiss Kane','Alain Poutre');
create table `MEDICAMENT`(`MED_DEPOTLEGAL` VARCHAR(10) not null,`MED_NOMCOMMERCIAL` VARCHAR(25),`FAM_CODE` VARCHAR(3) not null,`MED_COMPOSITION` VARCHAR(255),`MED_EFFETS` VARCHAR(255),`MED_CONTREINDIC` VARCHAR(255),`MED_PRIXECHANTILLON` FLOAT,primary key(`MED_DEPOTLEGAL`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('3MYC7','TRIMYCINE','CRT','Triamcinolone (ac�tonide) + N�omycine + Nystatine','Ce m�dicament est un cortico�de � activit� forte ou tr�s forte associ� � un antibiotique et un antifongique, utilis� en application locale dans certaines atteintes cutan�es surinfect�es.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants, d\'infections de la peau ou de parasitisme non trait�s, d\'acn�. Ne pas appliquer sur une plaie, ni sous un pansement occlusif.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('ADIMOL9','ADIMOL','ABP','Amoxicilline + Acide clavulanique','Ce m�dicament, plus puissant que les p�nicillines simples, est utilis� pour traiter des infections bact�riennes sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux p�nicillines ou aux c�phalosporines.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('AMOPIL7','AMOPIL','ABP','Amoxicilline','Ce m�dicament, plus puissant que les p�nicillines simples, est utilis� pour traiter des infections bact�riennes sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux p�nicillines. Il doit �tre administr� avec prudence en cas d\'allergie aux c�phalosporines.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('AMOX45','AMOXAR','ABP','Amoxicilline','Ce m�dicament, plus puissant que les p�nicillines simples, est utilis� pour traiter des infections bact�riennes sp�cifiques.','La prise de ce m�dicament peut rendre positifs les tests de d�pistage du dopage.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('AMOXIG12','AMOXI G�','ABP','Amoxicilline','Ce m�dicament, plus puissant que les p�nicillines simples, est utilis� pour traiter des infections bact�riennes sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux p�nicillines. Il doit �tre administr� avec prudence en cas d\'allergie aux c�phalosporines.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('APATOUX22','APATOUX Vitamine C','ALO','Tyrothricine + T�traca�ne + Acide ascorbique (Vitamine C)','Ce m�dicament est utilis� pour traiter les affections de la bouche et de la gorge.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants, en cas de ph�nylc�tonurie et chez l\'enfant de moins de 6 ans.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('BACTIG10','BACTIGEL','ABC','Erythromycine','Ce m�dicament est utilis� en application locale pour traiter l\'acn� et les infections cutan�es bact�riennes associ�es.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux antibiotiques de la famille des macrolides ou des lincosanides.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('BACTIV13','BACTIVIL','AFM','Erythromycine','Ce m�dicament est utilis� pour traiter des infections bact�riennes sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux macrolides (dont le chef de file est l\'�rythromycine).',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('BITALV','BIVALIC','AAA','Dextropropoxyph�ne + Parac�tamol','Ce m�dicament est utilis� pour traiter les douleurs d\'intensit� mod�r�e ou intense.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux m�dicaments de cette famille, d\'insuffisance h�patique ou d\'insuffisance r�nale.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('CARTION6','CARTION','AAA','Acide ac�tylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Parac�tamol','Ce m�dicament est utilis� dans le traitement symptomatique de la douleur ou de la fi�vre.','Ce m�dicament est contre-indiqu� en cas de troubles de la coagulation (tendances aux h�morragies), d\'ulc�re gastroduod�nal, maladies graves du foie.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('CLAZER6','CLAZER','AFM','Clarithromycine','Ce m�dicament est utilis� pour traiter des infections bact�riennes sp�cifiques. Il est �galement utilis� dans le traitement de l\'ulc�re gastro-duod�nal, en association avec d\'autres m�dicaments.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux macrolides (dont le chef de file est l\'�rythromycine).',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('DEPRIL9','DEPRAMIL','AIM','Clomipramine','Ce m�dicament est utilis� pour traiter les �pisodes d�pressifs s�v�res, certaines douleurs rebelles, les troubles obsessionnels compulsifs et certaines �nur�sies chez l\'enfant.','Ce m�dicament est contre-indiqu� en cas de glaucome ou d\'ad�nome de la prostate, d\'infarctus r�cent, ou si vous avez re�u un traitement par IMAO durant les 2 semaines pr�c�dentes ou en cas d\'allergie aux antid�presseurs imipraminiques.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('DIMIRTAM6','DIMIRTAM','AAC','Mirtazapine','Ce m�dicament est utilis� pour traiter les �pisodes d�pressifs s�v�res.','La prise de ce produit est contre-indiqu�e en cas de d\'allergie � l\'un des constituants.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('DOLRIL7','DOLORIL','AAA','Acide ac�tylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Parac�tamol','Ce m�dicament est utilis� dans le traitement symptomatique de la douleur ou de la fi�vre.','Ce m�dicament est contre-indiqu� en cas d\'allergie au parac�tamol ou aux salicylates.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('DORNOM8','NORMADOR','HYP','Doxylamine','Ce m�dicament est utilis� pour traiter l\'insomnie chez l\'adulte.','Ce m�dicament est contre-indiqu� en cas de glaucome, de certains troubles urinaires (r�tention urinaire) et chez l\'enfant de moins de 15 ans.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('EQUILARX6','EQUILAR','AAH','M�clozine','Ce m�dicament est utilis� pour traiter les vertiges et pour pr�venir le mal des transports.','Ce m�dicament ne doit pas �tre utilis� en cas d\'allergie au produit, en cas de glaucome ou de r�tention urinaire.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('EVILR7','EVEILLOR','PSA','Adrafinil','Ce m�dicament est utilis� pour traiter les troubles de la vigilance et certains symptomes neurologiques chez le sujet ag�.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('INSXT5','INSECTIL','AH','Diph�nydramine','Ce m�dicament est utilis� en application locale sur les piq�res d\'insecte et l\'urticaire.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux antihistaminiques.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('JOVAI8','JOVENIL','AFM','Josamycine','Ce m�dicament est utilis� pour traiter des infections bact�riennes sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux macrolides (dont le chef de file est l\'�rythromycine).',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('LIDOXY23','LIDOXYTRACINE','AFC','Oxyt�tracycline +Lidoca�ne','Ce m�dicament est utilis� en injection intramusculaire pour traiter certaines infections sp�cifiques.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants. Il ne doit pas �tre associ� aux r�tino�des.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('LITHOR12','LITHORINE','AP','Lithium','Ce m�dicament est indiqu� dans la pr�vention des psychoses maniaco-d�pressives ou pour traiter les �tats maniaques.','Ce m�dicament ne doit pas �tre utilis� si vous �tes allergique au lithium. Avant de prendre ce traitement, signalez � votre m�decin traitant si vous souffrez d\'insuffisance r�nale, ou si vous avez un r�gime sans sel.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('PARMOL16','PARMOCODEINE','AA','Cod�ine + Parac�tamol','Ce m�dicament est utilis� pour le traitement des douleurs lorsque des antalgiques simples ne sont pas assez efficaces.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants, chez l\'enfant de moins de 15 Kg, en cas d\'insuffisance h�patique ou respiratoire, d\'asthme, de ph�nylc�tonurie et chez la femme qui allaite.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('PHYSOI8','PHYSICOR','PSA','Sulbutiamine','Ce m�dicament est utilis� pour traiter les baisses d\'activit� physique ou psychique, souvent dans un contexte de d�pression.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('PIRIZ8','PIRIZAN','ABA','Pyrazinamide','Ce m�dicament est utilis�, en association � d\'autres antibiotiques, pour traiter la tuberculose.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants, d\'insuffisance r�nale ou h�patique, d\'hyperuric�mie ou de porphyrie.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('POMDI20','POMADINE','AO','Bacitracine','Ce m�dicament est utilis� pour traiter les infections oculaires de la surface de l\'oeil.','Ce m�dicament est contre-indiqu� en cas d\'allergie aux antibiotiques appliqu�s localement.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('TROXT21','TROXADET','AIN','Parox�tine','Ce m�dicament est utilis� pour traiter la d�pression et les troubles obsessionnels compulsifs. Il peut �galement �tre utilis� en pr�vention des crises de panique avec ou sans agoraphobie.','Ce m�dicament est contre-indiqu� en cas d\'allergie au produit.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('TXISOL22','TOUXISOL Vitamine C','ALO','Tyrothricine + Acide ascorbique (Vitamine C)','Ce m�dicament est utilis� pour traiter les affections de la bouche et de la gorge.','Ce m�dicament est contre-indiqu� en cas d\'allergie � l\'un des constituants et chez l\'enfant de moins de 6 ans.',null);
insert into `MEDICAMENT`(`MED_DEPOTLEGAL`,`MED_NOMCOMMERCIAL`,`FAM_CODE`,`MED_COMPOSITION`,`MED_EFFETS`,`MED_CONTREINDIC`,`MED_PRIXECHANTILLON`) values('URIEG6','URIREGUL','AUM','Fosfomycine trom�tamol','Ce m�dicament est utilis� pour traiter les infections urinaires simples chez la femme de moins de 65 ans.','La prise de ce m�dicament est contre-indiqu�e en cas d\'allergie � l\'un des constituants et d\'insuffisance r�nale.',null);
create table `OFFRIR`(`VIS_MATRICULE` VARCHAR(10) not null,`RAP_NUM` INT not null,`MED_DEPOTLEGAL` VARCHAR(10) not null,`OFF_QTE` SMALLINT,primary key(`VIS_MATRICULE`,`RAP_NUM`,`MED_DEPOTLEGAL`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `OFFRIR`(`VIS_MATRICULE`,`RAP_NUM`,`MED_DEPOTLEGAL`,`OFF_QTE`) values('a17',4,'3MYC7',3);
insert into `OFFRIR`(`VIS_MATRICULE`,`RAP_NUM`,`MED_DEPOTLEGAL`,`OFF_QTE`) values('a17',4,'AMOX45',12);
create table `POSSEDER`(`PRA_NUM` SMALLINT not null,`SPE_CODE` VARCHAR(5) not null,`POS_DIPLOME` VARCHAR(10),`POS_COEFPRESCRIPTION` FLOAT,primary key(`PRA_NUM`,`SPE_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `PRATICIEN`(`PRA_NUM` SMALLINT not null,`PRA_NOM` VARCHAR(25),`PRA_PRENOM` VARCHAR(30),`PRA_ADRESSE` VARCHAR(50),`PRA_CP` VARCHAR(5),`PRA_VILLE` VARCHAR(25),`PRA_COEFNOTORIETE` FLOAT,`TYP_CODE` VARCHAR(3) not null,primary key(`PRA_NUM`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(1,'Notini','Alain','114 r Authie','85000','LA ROCHE SUR YON',290.03,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(2,'Gosselin','Albert','13 r Devon','41000','BLOIS',307.49,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(3,'Delahaye','Andr�','36 av 6 Juin','25000','BESANCON',185.79,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(4,'Leroux','Andr�','47 av Robert Schuman','60000','BEAUVAIS',172.04,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(5,'Desmoulins','Anne','31 r St Jean','30000','NIMES',94.75,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(6,'Mouel','Anne','27 r Auvergne','80000','AMIENS',45.2,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(7,'Desgranges-Lentz','Antoine','1 r Albert de Mun','29000','MORLAIX',20.07,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(8,'Marcouiller','Arnaud','31 r St Jean','68000','MULHOUSE',396.52,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(9,'Dupuy','Benoit','9 r Demolombe','34000','MONTPELLIER',395.66,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(10,'Lerat','Bernard','31 r St Jean','59000','LILLE',257.79,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(11,'Mar�ais-Lefebvre','Bertrand','86Bis r Basse','67000','STRASBOURG',450.96,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(12,'Boscher','Bruno','94 r Falaise','10000','TROYES',356.14,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(13,'Morel','Catherine','21 r Chateaubriand','75000','PARIS',379.57,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(14,'Guivarch','Chantal','4 av G�n Laperrine','45000','ORLEANS',114.56,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(15,'Bessin-Grosdoit','Christophe','92 r Falaise','6000','NICE',222.06,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(16,'Rossa','Claire','14 av Thi�s','6000','NICE',529.78,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(17,'Cauchy','Denis','5 av Ste Th�r�se','11000','NARBONNE',458.82,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(18,'Gaff�','Dominique','9 av 1�re Arm�e Fran�aise','35000','RENNES',213.4,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(19,'Guenon','Dominique','98 bd Mar Lyautey','44000','NANTES',175.89,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(20,'Pr�vot','Dominique','29 r Lucien Nelle','87000','LIMOGES',151.36,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(21,'Houchard','Eliane','9 r Demolombe','49100','ANGERS',436.96,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(22,'Desmons','Elisabeth','51 r Berni�res','29000','QUIMPER',281.17,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(23,'Flament','Elisabeth','11 r Pasteur','35000','RENNES',315.6,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(24,'Goussard','Emmanuel','9 r Demolombe','41000','BLOIS',40.72,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(25,'Desprez','Eric','9 r Vaucelles','33000','BORDEAUX',406.85,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(26,'Coste','Evelyne','29 r Lucien Nelle','19000','TULLE',441.87,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(27,'Lefebvre','Fr�d�ric','2 pl Wurzburg','55000','VERDUN',573.63,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(28,'Lem�e','Fr�d�ric','29 av 6 Juin','56000','VANNES',326.4,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(29,'Martin','Fr�d�ric','B�t A 90 r Bayeux','70000','VESOUL',506.06,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(30,'Marie','Fr�d�rique','172 r Caponi�re','70000','VESOUL',313.31,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(31,'Rosenstech','Genevi�ve','27 r Auvergne','75000','PARIS',366.82,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(32,'Pontavice','Ghislaine','8 r Gaillon','86000','POITIERS',265.58,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(33,'Leveneur-Mosquet','Guillaume','47 av Robert Schuman','64000','PAU',184.97,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(34,'Blanchais','Guy','30 r Authie','8000','SEDAN',502.48,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(35,'Leveneur','Hugues','7 pl St Gilles','62000','ARRAS',7.39,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(36,'Mosquet','Isabelle','22 r Jules Verne','76000','ROUEN',77.1,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(37,'Giraudon','Jean-Christophe','1 r Albert de Mun','38100','VIENNE',92.62,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(38,'Marie','Jean-Claude','26 r H�rouville','69000','LYON',120.1,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(39,'Maury','Jean-Fran�ois','5 r Pierre Girard','71000','CHALON SUR SAONE',13.73,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(40,'Dennel','Jean-Louis','7 pl St Gilles','28000','CHARTRES',550.69,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(41,'Ain','Jean-Pierre','4 r�sid Olympia','2000','LAON',5.59,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(42,'Chemery','Jean-Pierre','51 pl Ancienne Boucherie','14000','CAEN',396.58,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(43,'Comoz','Jean-Pierre','35 r Auguste Lechesne','18000','BOURGES',340.35,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(44,'Desfaudais','Jean-Pierre','7 pl St Gilles','29000','BREST',71.76,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(45,'Phan','J�rôme','9 r Clos Caillet','79000','NIORT',451.61,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(46,'Riou','Line','43 bd G�n Vanier','77000','MARNE LA VALLEE',193.25,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(47,'Chubilleau','Louis','46 r Eglise','17000','SAINTES',202.07,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(48,'Lebrun','Lucette','178 r Auge','54000','NANCY',410.41,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(49,'Goessens','Marc','6 av 6 Juin','39000','DOLE',548.57,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(50,'Laforge','Marc','5 r�sid Prairie','50000','SAINT LO',265.05,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(51,'Millereau','Marc','36 av 6 Juin','72000','LA FERTE BERNARD',430.42,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(52,'Dauverne','Marie-Christine','69 av Charlemagne','21000','DIJON',281.05,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(53,'Vittorio','Myriam','3 pl Champlain','94000','BOISSY SAINT LEGER',356.23,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(54,'Lapasset','Nhieu','31 av 6 Juin','52000','CHAUMONT',107,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(55,'Plantet-Besnier','Nicole','10 av 1�re Arm�e Fran�aise','86000','CHATELLEREAULT',369.94,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(56,'Chubilleau','Pascal','3 r Hastings','15000','AURRILLAC',290.75,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(57,'Robert','Pascal','31 r St Jean','93000','BOBIGNY',162.41,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(58,'Jean','Pascale','114 r Authie','49100','SAUMUR',375.52,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(59,'Chanteloube','Patrice','14 av Thi�s','13000','MARSEILLE',478.01,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(60,'Lecuirot','Patrice','r�sid St P�res 55 r Pigaci�re','54000','NANCY',239.66,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(61,'Gandon','Patrick','47 av Robert Schuman','37000','TOURS',599.06,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(62,'Mirouf','Patrick','22 r Puits Picard','74000','ANNECY',458.42,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(63,'Boireaux','Philippe','14 av Thi�s','10000','CHALON EN CHAMPAGNE',454.48,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(64,'Cendrier','Philippe','7 pl St Gilles','12000','RODEZ',164.16,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(65,'Duhamel','Philippe','114 r Authie','34000','MONTPELLIER',98.62,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(66,'Grigy','Philippe','15 r M�lingue','44000','CLISSON',285.1,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(67,'Linard','Philippe','1 r Albert de Mun','81000','ALBI',486.3,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(68,'Lozier','Philippe','8 r Gaillon','31000','TOULOUSE',48.4,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(69,'Dech�tre','Pierre','63 av Thi�s','23000','MONTLUCON',253.75,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(70,'Goessens','Pierre','22 r Jean Romain','40000','MONT DE MARSAN',426.19,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(71,'Lem�nager','Pierre','39 av 6 Juin','57000','METZ',118.7,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(72,'N�e','Pierre','39 av 6 Juin','82000','MONTAUBAN',72.54,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(73,'Guyot','Pierre-Laurent','43 bd G�n Vanier','48000','MENDE',352.31,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(74,'Chauchard','Roger','9 r Vaucelles','13000','MARSEILLE',552.19,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(75,'Mabire','Roland','11 r Boutiques','67000','STRASBOURG',422.39,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(76,'Leroy','Soazig','45 r Boutiques','61000','ALENCON',570.67,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(77,'Guyot','St�phane','26 r H�rouville','46000','FIGEAC',28.85,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(78,'Delposen','Sylvain','39 av 6 Juin','27000','DREUX',292.01,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(79,'Rault','Sylvie','15 bd Richemond','2000','SOISSON',526.6,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(80,'Renouf','Sylvie','98 bd Mar Lyautey','88000','EPINAL',425.24,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(81,'Alliet-Grach','Thierry','14 av Thi�s','7000','PRIVAS',451.31,'MH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(82,'Bayard','Thierry','92 r Falaise','42000','SAINT ETIENNE',271.71,'MV');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(83,'Gauchet','Thierry','7 r Desmoueux','38100','GRENOBLE',406.1,'PS');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(84,'Bobichon','Tristan','219 r Caponi�re','9000','FOIX',218.36,'PH');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(85,'Duchemin-Laniel','V�ronique','130 r St Jean','33000','LIBOURNE',265.61,'PO');
insert into `PRATICIEN`(`PRA_NUM`,`PRA_NOM`,`PRA_PRENOM`,`PRA_ADRESSE`,`PRA_CP`,`PRA_VILLE`,`PRA_COEFNOTORIETE`,`TYP_CODE`) values(86,'Laurent','Youn�s','34 r Demolombe','53000','MAYENNE',496.1,'MH');
create table `PRESCRIRE`(`MED_DEPOTLEGAL` VARCHAR(10) not null,`TIN_CODE` VARCHAR(5) not null,`DOS_CODE` VARCHAR(10) not null,`PRE_POSOLOGIE` VARCHAR(40),primary key(`MED_DEPOTLEGAL`,`TIN_CODE`,`DOS_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `PRESENTATION`(`PRE_CODE` VARCHAR(2) not null,`PRE_LIBELLE` VARCHAR(20),primary key(`PRE_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `RAPPORT_VISITE`(`VIS_MATRICULE` VARCHAR(10) not null,`RAP_NUM` INT not null,`PRA_NUM` SMALLINT not null,`RAP_DATE` DATETIME,`RAP_BILAN` VARCHAR(255),`RAP_MOTIF` VARCHAR(255),primary key(`VIS_MATRICULE`,`RAP_NUM`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `RAPPORT_VISITE`(`VIS_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`RAP_DATE`,`RAP_BILAN`,`RAP_MOTIF`) values('a131',3,23,'2002-4-18','M�decin curieux, � recontacer en d�cembre pour r�union','Actualisation annuelle');
insert into `RAPPORT_VISITE`(`VIS_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`RAP_DATE`,`RAP_BILAN`,`RAP_MOTIF`) values('a131',7,41,'2003-3-23','RAS
Changement de tel : 05 89 89 89 89','Rapport Annuel');
insert into `RAPPORT_VISITE`(`VIS_MATRICULE`,`RAP_NUM`,`PRA_NUM`,`RAP_DATE`,`RAP_BILAN`,`RAP_MOTIF`) values('a17',4,4,'2003-5-21','Changement de direction, red�finition de la politique m�dicamenteuse, recours au g�n�rique','Baisse activit�');
create table `REALISER`(`AC_NUM` INT not null,`VIS_MATRICULE` VARCHAR(10) not null,`REA_MTTFRAIS` FLOAT,primary key(`AC_NUM`,`VIS_MATRICULE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `REGION`(`REG_CODE` VARCHAR(2) not null,`SEC_CODE` VARCHAR(1) not null,`REG_NOM` VARCHAR(50),primary key(`REG_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AL','E','Alsace Lorraine');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AQ','S','Aquitaine');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('AU','P','Auvergne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BG','O','Bretagne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BN','O','Basse Normandie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('BO','E','Bourgogne');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('CA','N','Champagne Ardennes');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('CE','P','Centre');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('FC','E','Franche Comt�');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('HN','N','Haute Normandie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('IF','P','Ile de France');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('LG','S','Languedoc');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('LI','P','Limousin');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('MP','S','Midi Pyr�n�e');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('NP','N','Nord Pas de Calais');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PA','S','Provence Alpes Cote d\'Azur');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PC','O','Poitou Charente');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PI','N','Picardie');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('PL','O','Pays de Loire');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('RA','E','Rhone Alpes');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('RO','S','Roussilon');
insert into `REGION`(`REG_CODE`,`SEC_CODE`,`REG_NOM`) values('VD','O','Vend�e');
create table `SECTEUR`(`SEC_CODE` VARCHAR(1) not null,`SEC_LIBELLE` VARCHAR(15),primary key(`SEC_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('E','Est');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('N','Nord');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('O','Ouest');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('P','Paris centre');
insert into `SECTEUR`(`SEC_CODE`,`SEC_LIBELLE`) values('S','Sud');
create table `SPECIALITE`(`SPE_CODE` VARCHAR(5) not null,`SPE_LIBELLE` VARCHAR(150),primary key(`SPE_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('ACP','anatomie et cytologie pathologiques');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('AMV','ang�iologie, m�decine vasculaire');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('ARC','anesth�siologie et r�animation chirurgicale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('BM','biologie m�dicale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CAC','cardiologie et affections cardio-vasculaires');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CCT','chirurgie cardio-vasculaire et thoracique');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CG','chirurgie g�n�rale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CMF','chirurgie maxillo-faciale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('COM','canc�rologie, oncologie m�dicale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('COT','chirurgie orthop�dique et traumatologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CPR','chirurgie plastique reconstructrice et esth�tique');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CU','chirurgie urologique');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('CV','chirurgie vasculaire');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('DN','diab�tologie-nutrition, nutrition');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('DV','dermatologie et v�n�r�ologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('EM','endocrinologie et m�tabolismes');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('ETD','�valuation et traitement de la douleur');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('GEH','gastro-ent�rologie et h�patologie (appareil digestif)');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('GMO','gyn�cologie m�dicale, obst�trique');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('GO','gyn�cologie-obst�trique');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('HEM','maladies du sang (h�matologie)');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MBS','m�decine et biologie du sport');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MDT','m�decine du travail');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MMO','m�decine manuelle - ost�opathie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MN','m�decine nucl�aire');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MPR','m�decine physique et de r�adaptation');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('MTR','m�decine tropicale, pathologie infectieuse et tropicale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('NEP','n�phrologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('NRC','neurochirurgie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('NRL','neurologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('ODM','orthop�die dento maxillo-faciale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('OPH','ophtalmologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('ORL','oto-rhino-laryngologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('PEA','psychiatrie de l\'enfant et de l\'adolescent');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('PME','p�diatrie maladies des enfants');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('PNM','pneumologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('PSC','psychiatrie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('RAD','radiologie (radiodiagnostic et imagerie m�dicale)');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('RDT','radioth�rapie (oncologie option radioth�rapie)');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('RGM','reproduction et gyn�cologie m�dicale');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('RHU','rhumatologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('STO','stomatologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('SXL','sexologie');
insert into `SPECIALITE`(`SPE_CODE`,`SPE_LIBELLE`) values('TXA','toxicomanie et alcoologie');
create table `Switchboard Items`(`SwitchboardID` INT not null,`ItemNumber` SMALLINT not null,`ItemText` VARCHAR(255),`Command` SMALLINT,`Argument` VARCHAR(255),primary key(`SwitchboardID`,`ItemNumber`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,0,'Gestion des comptes rendus',null,'Par d�faut');
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,1,'Comptes-Rendus',3,'RAPPORT_VISITE');
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,2,'Visiteurs',3,'F_VISITEUR');
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,3,'Praticiens',3,'F_PRATICIEN');
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,4,'Medicaments',3,'F_MEDICAMENT');
insert into `Switchboard Items`(`SwitchboardID`,`ItemNumber`,`ItemText`,`Command`,`Argument`) values(1,5,'Quitter',8,'quitter');
create table `TRAVAILLER`(`VIS_MATRICULE` VARCHAR(10) not null,`JJMMAA` DATETIME not null,`REG_CODE` VARCHAR(2) not null,`TRA_ROLE` VARCHAR(11),primary key(`JJMMAA`,`VIS_MATRICULE`,`REG_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p49','1977-10-3','CE','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('k53','1983-3-23','CA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('r24','1984-7-29','BN','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('g53','1985-10-2','BG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a55','1987-7-17','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('m35','1987-10-6','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e39','1988-4-26','IF','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('c14','1989-2-1','PA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e22','1989-3-24','AL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p7','1990-3-1','RO','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('r58','1990-6-30','BG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('m45','1990-10-13','AL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e5','1990-11-27','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('t60','1991-3-29','CE','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('c54','1991-4-9','AL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p8','1991-6-23','BO','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a17','1991-8-26','RA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e52','1991-10-31','HN','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('d13','1991-12-5','PL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('k53','1992-4-3','AL','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('c3','1992-5-5','CA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('n58','1992-8-30','CE','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('s21','1992-9-25','LI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('h40','1992-11-1','CA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a131','1992-12-11','BN','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p40','1992-12-14','BN','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('j50','1992-12-16','NP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p32','1992-12-24','IF','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('h13','1993-5-8','LI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e24','1993-5-17','AL','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('f21','1993-6-8','RA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('h35','1993-8-26','AU','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b34','1993-12-6','CE','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('f4','1994-5-3','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b25','1994-7-3','PL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('t55','1994-11-29','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p42','1994-12-12','PI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('n59','1994-12-19','PI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('o26','1995-1-5','LG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('l14','1995-2-2','PL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('t43','1995-3-9','BO','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a55','1995-5-19','RO','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('l23','1995-6-5','PC','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b59','1995-10-21','RA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('s10','1995-11-14','FC','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e5','1995-11-27','MP','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('g7','1996-1-13','LI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('g19','1996-1-18','IF','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e49','1996-2-19','MP','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('l56','1996-2-27','FC','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('n42','1996-3-6','HN','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b13','1996-3-11','AL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a131','1996-5-27','BG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('k4','1996-11-21','LG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('l46','1997-1-24','PL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('c14','1997-2-1','PA','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('f39','1997-2-15','RA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b16','1997-3-21','BG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p6','1997-3-30','AQ','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('t47','1997-8-29','PI','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('q17','1997-9-6','BN','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a17','1997-9-19','RA','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b4','1997-9-25','AQ','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('d51','1997-11-18','FC','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b50','1998-1-18','PA','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('j45','1998-2-25','CA','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('h30','1998-4-26','IF','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('r24','1998-5-25','BN','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('j8','1998-6-18','IF','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p41','1998-7-27','PC','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a93','1999-1-2','PC','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b19','1999-1-31','PL','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('g30','1999-3-27','PI','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('m45','1999-4-8','AL','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b34','1999-6-18','CE','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('p40','1999-7-17','BN','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('a55','1999-8-21','RO','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b25','2000-1-1','PL','D�l�gu�');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e24','2000-2-29','AL','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('b28','2000-8-2','LG','Visiteur');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('g30','2000-10-31','PI','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('e5','2000-11-27','AQ','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('c14','2001-3-3','PA','Responsable');
insert into `TRAVAILLER`(`VIS_MATRICULE`,`JJMMAA`,`REG_CODE`,`TRA_ROLE`) values('d51','2002-3-20','FC','Responsable');
create table `ENGINE_INDIVIDU`(`TIN_CODE` VARCHAR(5) not null,`TIN_LIBELLE` VARCHAR(50),primary key(`TIN_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
create table `ENGINE_PRATICIEN`(`TYP_CODE` VARCHAR(3) not null,`TYP_LIBELLE` VARCHAR(25),`TYP_LIEU` VARCHAR(35),primary key(`TYP_CODE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `ENGINE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('MH','M�decin Hospitalier','Hopital ou clinique');
insert into `ENGINE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('MV','M�decine de Ville','Cabinet');
insert into `ENGINE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PH','Pharmacien Hospitalier','Hopital ou clinique');
insert into `ENGINE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PO','Pharmacien Officine','Pharmacie');
insert into `ENGINE_PRATICIEN`(`TYP_CODE`,`TYP_LIBELLE`,`TYP_LIEU`) values('PS','Personnel de sant�','Centre param�dical');
create table `VISITEUR`(`VIS_MATRICULE` VARCHAR(10) not null,`VIS_NOM` VARCHAR(25),`Vis_PRENOM` VARCHAR(50),`VIS_ADRESSE` VARCHAR(50),`VIS_CP` VARCHAR(5),`VIS_VILLE` VARCHAR(30),`VIS_DATEEMBAUCHE` DATETIME,`SEC_CODE` VARCHAR(1),`LAB_CODE` VARCHAR(2) not null,primary key(`VIS_MATRICULE`)) ENGINE=INNODB DEFAULT CHARSET=latin1;
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('a131','Villechalane','Louis','8 cours Lafontaine','29000','BREST','1992-12-11',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('a17','Andre','David','1 r Aimon de Chiss�e','38100','GRENOBLE','1991-8-26',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('a55','Bedos','Christian','1 r B�n�dictins','65000','TARBES','1987-7-17',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('a93','Tusseau','Louis','22 r Renou','86000','POITIERS','1999-1-2',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b13','Bentot','Pascal','11 av 6 Juin','67000','STRASBOURG','1996-3-11',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b16','Bioret','Luc','1 r Linne','35000','RENNES','1997-3-21',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b19','Bunisset','Francis','10 r Nicolas Chorier','85000','LA ROCHE SUR YON','1999-1-31',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b25','Bunisset','Denise','1 r Lionne','49100','ANGERS','1994-7-3',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b28','Cacheux','Bernard','114 r Authie','34000','MONTPELLIER','2000-8-2',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b34','Cadic','Eric','123 r Caponi�re','41000','BLOIS','1993-12-6','P','SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b4','Charoze','Catherine','100 pl G�ants','33000','BORDEAUX','1997-9-25',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b50','Clepkens','Christophe','12 r F�d�rico Garcia Lorca','13000','MARSEILLE','1998-1-18',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('b59','Cottin','Vincenne','36 sq Capucins','5000','GAP','1995-10-21',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('c14','Daburon','Fran�ois','13 r Champs Elys�es','6000','NICE','1989-2-1','S','SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('c3','De','Philippe','13 r Charles Peguy','10000','TROYES','1992-5-5',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('c54','Debelle','Michel','181 r Caponi�re','88000','EPINAL','1991-4-9',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('d13','Debelle','Jeanne','134 r Stalingrad','44000','NANTES','1991-12-5',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('d51','Debroise','Michel','2 av 6 Juin','70000','VESOUL','1997-11-18','E','GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e22','Desmarquest','Nathalie','14 r F�d�rico Garcia Lorca','54000','NANCY','1989-3-24',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e24','Desnost','Pierre','16 r Barral de Montferrat','55000','VERDUN','1993-5-17','E','SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e39','Dudouit','Fr�d�ric','18 quai Xavier Jouvin','75000','PARIS','1988-4-26',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e49','Duncombe','Claude','19 av Alsace Lorraine','9000','FOIX','1996-2-19',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e5','Enault-Pascreau','C�line','25B r Stalingrad','40000','MONT DE MARSAN','1990-11-27','S','GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('e52','Eynde','Val�rie','3 r Henri Moissan','76000','ROUEN','1991-10-31',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('f21','Finck','Jacques','rte Montreuil Bellay','74000','ANNECY','1993-6-8',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('f39','Fr�mont','Fernande','4 r Jean Giono','69000','LYON','1997-2-15',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('f4','Gest','Alain','30 r Authie','46000','FIGEAC','1994-5-3',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('g19','Gheysen','Galassus','32 bd Mar Foch','75000','PARIS','1996-1-18',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('g30','Girard','Yvon','31 av 6 Juin','80000','AMIENS','1999-3-27','N','GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('g53','Gombert','Luc','32 r Emile Gueymard','56000','VANNES','1985-10-2',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('g7','Guindon','Caroline','40 r Mar Montgomery','87000','LIMOGES','1996-1-13',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('h13','Guindon','Fran�ois','44 r Picoti�re','19000','TULLE','1993-5-8',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('h30','Igigabel','Guy','33 gal Arlequin','94000','CRETEIL','1998-4-26',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('h35','Jourdren','Pierre','34 av Jean Perrot','15000','AURRILLAC','1993-8-26',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('h40','Juttard','Pierre-Raoul','34 cours Jean Jaur�s','8000','SEDAN','1992-11-1',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('j45','Labour�-Morel','Saout','38 cours Berriat','52000','CHAUMONT','1998-2-25','N','SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('j50','Landr�','Philippe','4 av G�n Laperrine','59000','LILLE','1992-12-16',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('j8','Langeard','Hugues','39 av Jean Perrot','93000','BAGNOLET','1998-6-18','P','GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('k4','Lanne','Bernard','4 r Bayeux','30000','NIMES','1996-11-21',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('k53','Le','No�l','4 av Beauvert','68000','MULHOUSE','1983-3-23',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('l14','Le','Jean','39 r Raspail','53000','LAVAL','1995-2-2',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('l23','Leclercq','Servane','11 r Quinconce','18000','BOURGES','1995-6-5',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('l46','Lecornu','Jean-Bernard','4 bd Mar Foch','72000','LA FERTE BERNARD','1997-1-24',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('l56','Lecornu','Ludovic','4 r Abel Servien','25000','BESANCON','1996-2-27',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('m35','Lejard','Agn�s','4 r Anthoard','82000','MONTAUBAN','1987-10-6',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('m45','Lesaulnier','Pascal','47 r Thiers','57000','METZ','1990-10-13',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('n42','Letessier','St�phane','5 chem Capuche','27000','EVREUX','1996-3-6',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('n58','Loirat','Didier','Les P�chers cit� Bourg la Croix','45000','ORLEANS','1992-8-30',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('n59','Maffezzoli','Thibaud','5 r Chateaubriand','2000','LAON','1994-12-19',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('o26','Mancini','Anne','5 r D\'Agier','48000','MENDE','1995-1-5',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p32','Marcouiller','G�rard','7 pl St Gilles','91000','ISSY LES MOULINEAUX','1992-12-24',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p40','Michel','Jean-Claude','5 r Gabriel P�ri','61000','FLERS','1992-12-14','O','SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p41','Montecot','Fran�oise','6 r Paul Val�ry','17000','SAINTES','1998-7-27',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p42','Notini','Veronique','5 r Lieut Chabal','60000','BEAUVAIS','1994-12-12',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p49','Onfroy','Den','5 r Sidonie Jacolin','37000','TOURS','1977-10-3',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p6','Pascreau','Charles','57 bd Mar Foch','64000','PAU','1997-3-30',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p7','Pernot','Claude-No�l','6 r Alexandre 1 de Yougoslavie','11000','NARBONNE','1990-3-1',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('p8','Perrier','Ma�tre','6 r Aubert Dubayet','71000','CHALON SUR SAONE','1991-6-23',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('q17','Petit','Jean-Louis','7 r Ernest Renan','50000','SAINT LO','1997-9-6',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('r24','Piquery','Patrick','9 r Vaucelles','14000','CAEN','1984-7-29','O','GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('r58','Quiquandon','Jo�l','7 r Ernest Renan','29000','QUIMPER','1990-6-30',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('s10','Retailleau','Josselin','88Bis r Saumuroise','39000','DOLE','1995-11-14',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('s21','Retailleau','Pascal','32 bd Ayrault','23000','MONTLUCON','1992-9-25',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('t43','Souron','Maryse','7B r Gay Lussac','21000','DIJON','1995-3-9',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('t47','Tiphagne','Patrick','7B r Gay Lussac','62000','ARRAS','1997-8-29',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('t55','Tr�het','Alain','7D chem Barral','12000','RODEZ','1994-11-29',null,'SW');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('t60','Tusseau','Josselin','63 r Bon Repos','28000','CHARTRES','1991-3-29',null,'GY');
insert into `VISITEUR`(`VIS_MATRICULE`,`VIS_NOM`,`Vis_PRENOM`,`VIS_ADRESSE`,`VIS_CP`,`VIS_VILLE`,`VIS_DATEEMBAUCHE`,`SEC_CODE`,`LAB_CODE`) values('zzz','swiss','bourdin',null,null,null,'2003-6-18',null,'BC');
alter table `PRESCRIRE` add foreign key (`MED_DEPOTLEGAL`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
alter table `INVITER` add foreign key (`AC_NUM`) references `ACTIVITE_COMPL`(`AC_NUM`);
alter table `PRATICIEN` add foreign key (`TYP_CODE`) references `ENGINE_PRATICIEN`(`TYP_CODE`);
alter table `FORMULER` add foreign key (`PRE_CODE`) references `PRESENTATION`(`PRE_CODE`);
alter table `OFFRIR` add foreign key (`MED_DEPOTLEGAL`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
alter table `PRESCRIRE` add foreign key (`TIN_CODE`) references `ENGINE_INDIVIDU`(`TIN_CODE`);
alter table `REGION` add foreign key (`SEC_CODE`) references `SECTEUR`(`SEC_CODE`);
alter table `FORMULER` add foreign key (`MED_DEPOTLEGAL`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
alter table `OFFRIR` add foreign key (`VIS_MATRICULE`,`RAP_NUM`) references `RAPPORT_VISITE`(`VIS_MATRICULE`,`RAP_NUM`);
alter table `TRAVAILLER` add foreign key (`REG_CODE`) references `REGION`(`REG_CODE`);
alter table `MEDICAMENT` add foreign key (`FAM_CODE`) references `FAMILLE`(`FAM_CODE`);
alter table `POSSEDER` add foreign key (`SPE_CODE`) references `SPECIALITE`(`SPE_CODE`);
alter table `CONSTITUER` add foreign key (`CMP_CODE`) references `COMPOSANT`(`CMP_CODE`);
alter table `VISITEUR` add foreign key (`LAB_CODE`) references `LABO`(`LAB_CODE`);
alter table `RAPPORT_VISITE` add foreign key (`PRA_NUM`) references `PRATICIEN`(`PRA_NUM`);
alter table `POSSEDER` add foreign key (`PRA_NUM`) references `PRATICIEN`(`PRA_NUM`);
alter table `TRAVAILLER` add foreign key (`VIS_MATRICULE`) references `VISITEUR`(`VIS_MATRICULE`);
alter table `RAPPORT_VISITE` add foreign key (`VIS_MATRICULE`) references `VISITEUR`(`VIS_MATRICULE`);
alter table `CONSTITUER` add foreign key (`MED_DEPOTLEGAL`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
alter table `INTERAGIR` add foreign key (`MED_PERTURBATEUR`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
alter table `PRESCRIRE` add foreign key (`DOS_CODE`) references `DOSAGE`(`DOS_CODE`);
alter table `REALISER` add foreign key (`AC_NUM`) references `ACTIVITE_COMPL`(`AC_NUM`);
alter table `INVITER` add foreign key (`PRA_NUM`) references `PRATICIEN`(`PRA_NUM`);
alter table `REALISER` add foreign key (`VIS_MATRICULE`) references `VISITEUR`(`VIS_MATRICULE`);
alter table `VISITEUR` add foreign key (`SEC_CODE`) references `SECTEUR`(`SEC_CODE`);
alter table `INTERAGIR` add foreign key (`MED_MED_PERTURBE`) references `MEDICAMENT`(`MED_DEPOTLEGAL`);
commit;
